### ISSUE TITLE
"Data available" date range not updating

### ISSUE THREAD

**Issue by wsjones** [agrc/Crash-web#49]
New crash data posted to the .ftp site are being automatically loaded, but the "Data available" date range on the website did not update.

**Comment by steveoh** [comment]
I am unsure what happened there. The script seems to have run successfully on sunday. I added some more logging since when I stepped through it while debugging it worked as expected.

**Comment by wsjones** [comment]
No, still not working.  I updated new data last week.  The data did not load into the website application and the data range did not update.

**Comment by steveoh** [comment]
I thought we spoke on the phone about this being a browser caching issue or you were looking at the wrong website.

**Comment by steveoh** [comment]
This should be working now. Reopen this next time you update and the date doesn't update.

**Comment by wsjones** [comment]
It looks like the crash data loaded, but the data range is still not
correct.  The date range should go through 11/31/2015.

**Comment by steveoh** [comment]
this should be workin on sunday. 

fixed by https://github.com/agrc/Crash-db/commit/45e69fa3b0a86fa83d9a775c31c0aedd2a776005
